//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/script/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""77da15fb-3eed-4381-a9f7-b412f29e9b46"",
            ""actions"": [
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""24b0856d-7adf-4b95-8196-4c41ee96bcaf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""a23124e5-175f-4116-a0b8-b7f5f8d3f68b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""1ce81e54-798c-41fa-ad8b-a3018d95e8f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""4d1ed8ac-8762-46d8-962a-2bd34cc28781"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlechaUp"",
                    ""type"": ""Button"",
                    ""id"": ""d852ce1a-49dc-41ac-8d83-8f1379172a1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlechasDown"",
                    ""type"": ""Button"",
                    ""id"": ""2983a799-72a9-4342-9136-901f7f501bab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlechaIzq"",
                    ""type"": ""Button"",
                    ""id"": ""4cb27cdf-ebfd-4047-b920-612727e7a2b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlechasDer"",
                    ""type"": ""Button"",
                    ""id"": ""917ced12-5331-4fbf-a222-2d79356ba0a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JLeft"",
                    ""type"": ""Value"",
                    ""id"": ""5fee65b0-28d5-4510-8349-c14699da03e7"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""JRight"",
                    ""type"": ""Value"",
                    ""id"": ""5cb618d5-d9e0-47eb-922c-ed97f963219e"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""4212c70b-45f0-4078-8183-6b1bbf5f9b45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""5f375c16-50ea-46c2-b3ae-9a3328284eb4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Value"",
                    ""id"": ""7826aea1-c3a0-48ed-83b1-d17508bdac8e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Value"",
                    ""id"": ""a413eb1d-e163-4811-9475-e0dc78db8074"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83a5506d-bec3-4285-8c31-60a13ca39c0a"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d4f779e-8358-4b23-8259-545dc855ad27"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5a1bd21-7579-48bd-b59f-1c8a279fb790"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ba82507-5e98-420f-aa2c-535ec503c98e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c43bcbc-c6da-4c88-9fa0-6a6361911be2"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f771f81-b2f9-4cb0-b6af-334e764891d1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlechaIzq"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ae203e6-f7e2-40aa-b0f7-5af28c75c125"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlechasDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06e9cb4f-c02e-4c90-9454-71b36f3df08d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlechasDer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ac7712-7676-498e-b50d-adb9243ef978"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlechasDer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5be8285e-d38f-4a77-a083-d41afc244809"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlechaUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27e5db27-654b-41a1-8cbf-776047777b49"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dd120ca-9fdf-4dd5-9656-2035ad8c1563"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7202ceba-6a80-4029-b0c0-b5c29d7acf4e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cdaeb8c-790d-4568-a676-51394dd9389e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf992b3b-0e22-47a9-ace6-b380406d38bb"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9a19115-8fe7-4e0f-a2c4-612a4ec409a9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1f7c1cb-211c-443f-b118-b9b419c17195"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b15001f-9d3a-43f2-8d0c-34db81b85970"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6d61acf-f5a1-40a9-a01f-3b35f3affafe"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0819bb43-a71a-41fc-914c-cb45e8fca745"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb0aa7de-092e-4e07-9bc9-277d3b7b7e71"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7840099-38e5-425a-ae57-fc1bd92e7d6f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_A = m_Gameplay.FindAction("A", throwIfNotFound: true);
        m_Gameplay_B = m_Gameplay.FindAction("B", throwIfNotFound: true);
        m_Gameplay_X = m_Gameplay.FindAction("X", throwIfNotFound: true);
        m_Gameplay_Y = m_Gameplay.FindAction("Y", throwIfNotFound: true);
        m_Gameplay_FlechaUp = m_Gameplay.FindAction("FlechaUp", throwIfNotFound: true);
        m_Gameplay_FlechasDown = m_Gameplay.FindAction("FlechasDown", throwIfNotFound: true);
        m_Gameplay_FlechaIzq = m_Gameplay.FindAction("FlechaIzq", throwIfNotFound: true);
        m_Gameplay_FlechasDer = m_Gameplay.FindAction("FlechasDer", throwIfNotFound: true);
        m_Gameplay_JLeft = m_Gameplay.FindAction("JLeft", throwIfNotFound: true);
        m_Gameplay_JRight = m_Gameplay.FindAction("JRight", throwIfNotFound: true);
        m_Gameplay_L1 = m_Gameplay.FindAction("L1", throwIfNotFound: true);
        m_Gameplay_R1 = m_Gameplay.FindAction("R1", throwIfNotFound: true);
        m_Gameplay_L2 = m_Gameplay.FindAction("L2", throwIfNotFound: true);
        m_Gameplay_R2 = m_Gameplay.FindAction("R2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_A;
    private readonly InputAction m_Gameplay_B;
    private readonly InputAction m_Gameplay_X;
    private readonly InputAction m_Gameplay_Y;
    private readonly InputAction m_Gameplay_FlechaUp;
    private readonly InputAction m_Gameplay_FlechasDown;
    private readonly InputAction m_Gameplay_FlechaIzq;
    private readonly InputAction m_Gameplay_FlechasDer;
    private readonly InputAction m_Gameplay_JLeft;
    private readonly InputAction m_Gameplay_JRight;
    private readonly InputAction m_Gameplay_L1;
    private readonly InputAction m_Gameplay_R1;
    private readonly InputAction m_Gameplay_L2;
    private readonly InputAction m_Gameplay_R2;
    public struct GameplayActions
    {
        private @PlayerControls m_Wrapper;
        public GameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @A => m_Wrapper.m_Gameplay_A;
        public InputAction @B => m_Wrapper.m_Gameplay_B;
        public InputAction @X => m_Wrapper.m_Gameplay_X;
        public InputAction @Y => m_Wrapper.m_Gameplay_Y;
        public InputAction @FlechaUp => m_Wrapper.m_Gameplay_FlechaUp;
        public InputAction @FlechasDown => m_Wrapper.m_Gameplay_FlechasDown;
        public InputAction @FlechaIzq => m_Wrapper.m_Gameplay_FlechaIzq;
        public InputAction @FlechasDer => m_Wrapper.m_Gameplay_FlechasDer;
        public InputAction @JLeft => m_Wrapper.m_Gameplay_JLeft;
        public InputAction @JRight => m_Wrapper.m_Gameplay_JRight;
        public InputAction @L1 => m_Wrapper.m_Gameplay_L1;
        public InputAction @R1 => m_Wrapper.m_Gameplay_R1;
        public InputAction @L2 => m_Wrapper.m_Gameplay_L2;
        public InputAction @R2 => m_Wrapper.m_Gameplay_R2;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @A.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnA;
                @B.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnB;
                @X.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnY;
                @FlechaUp.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaUp;
                @FlechaUp.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaUp;
                @FlechaUp.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaUp;
                @FlechasDown.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDown;
                @FlechasDown.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDown;
                @FlechasDown.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDown;
                @FlechaIzq.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaIzq;
                @FlechaIzq.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaIzq;
                @FlechaIzq.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechaIzq;
                @FlechasDer.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDer;
                @FlechasDer.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDer;
                @FlechasDer.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnFlechasDer;
                @JLeft.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJLeft;
                @JLeft.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJLeft;
                @JLeft.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJLeft;
                @JRight.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJRight;
                @JRight.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJRight;
                @JRight.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJRight;
                @L1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL1;
                @R1.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR1;
                @L2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnL2;
                @R2.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnR2;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @FlechaUp.started += instance.OnFlechaUp;
                @FlechaUp.performed += instance.OnFlechaUp;
                @FlechaUp.canceled += instance.OnFlechaUp;
                @FlechasDown.started += instance.OnFlechasDown;
                @FlechasDown.performed += instance.OnFlechasDown;
                @FlechasDown.canceled += instance.OnFlechasDown;
                @FlechaIzq.started += instance.OnFlechaIzq;
                @FlechaIzq.performed += instance.OnFlechaIzq;
                @FlechaIzq.canceled += instance.OnFlechaIzq;
                @FlechasDer.started += instance.OnFlechasDer;
                @FlechasDer.performed += instance.OnFlechasDer;
                @FlechasDer.canceled += instance.OnFlechasDer;
                @JLeft.started += instance.OnJLeft;
                @JLeft.performed += instance.OnJLeft;
                @JLeft.canceled += instance.OnJLeft;
                @JRight.started += instance.OnJRight;
                @JRight.performed += instance.OnJRight;
                @JRight.canceled += instance.OnJRight;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnFlechaUp(InputAction.CallbackContext context);
        void OnFlechasDown(InputAction.CallbackContext context);
        void OnFlechaIzq(InputAction.CallbackContext context);
        void OnFlechasDer(InputAction.CallbackContext context);
        void OnJLeft(InputAction.CallbackContext context);
        void OnJRight(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
    }
}
